export const profile = {
  name: "Vishwajith C R",
  shortName: "Vishwajith",
  title: "Senior AI Engineer",
  location: "Bengaluru, Karnataka, India",
  email: "vishwa.jith360@gmail.com",
  phone: "+91-8050997792",
  linkedin: "https://www.linkedin.com/in/vishwajith-cr/",
  github: "https://github.com/Vishwa360",
  heroTitle: "Building production GenAI, RAG, and AI governance systems for enterprise teams.",
  summary:
    "Senior AI Engineer with 11+ years across network engineering, data science, and applied AI. Experienced in shipping production-grade GenAI assistants, multimodal RAG systems, forecasting models, and operational ML solutions across telecom, finance, FMCG, and banking domains.",
  shortBio:
    "I design and deploy practical AI systems that improve decision-making, automate workflows, and hold up in production.",
  stats: [
    { value: "11+", label: "Years across AI, data, and network engineering" },
    { value: "4", label: "Enterprise domains served" },
    { value: "69%", label: "Productivity gain on agentic banking workflows" },
    { value: "35%", label: "Operational efficiency improvement on AI automation" },
  ],
  focusAreas: [
    {
      title: "Generative AI Systems",
      description: "Agentic assistants, multimodal RAG, conversational AI, summarization, and enterprise copilots.",
    },
    {
      title: "Production ML",
      description: "Forecasting, anomaly detection, monitoring, retraining, and end-to-end deployment workflows.",
    },
    {
      title: "AI Governance",
      description: "OpenPages and watsonx.governance workflows for transparency, compliance, and explainability.",
    },
    {
      title: "Platform Engineering",
      description: "FastAPI, Docker, OpenShift, cloud-native deployment, and model-serving patterns.",
    },
  ],
  capabilities: [
    "Multimodal RAG",
    "Agentic AI",
    "Text2SQL",
    "Text2MDX",
    "Time Series Forecasting",
    "Anomaly Detection",
    "AI Governance",
    "Model Monitoring",
    "FastAPI",
    "Docker",
    "OpenShift",
    "LangGraph",
  ],
  education: [
    {
      school: "Liverpool John Moores University",
      degree: "Master of Science (MSc) in Data Science",
      year: "2021",
      format: "Online",
    },
    {
      school: "International Institute of Information Technology, Bangalore",
      degree: "Post Graduate Diploma in Data Science",
      year: "2019",
      format: "Online",
    },
    {
      school: "PES University, Bangalore",
      degree: "Bachelor of Engineering in Telecommunications Engineering",
      year: "2014",
      format: "Full-time",
    },
  ],
  certifications: [],
  languages: ["English", "Kannada", "Hindi", "Telugu"],
  links: [
    { label: "LinkedIn", href: "https://www.linkedin.com/in/vishwajith-cr/" },
    { label: "GitHub", href: "https://github.com/Vishwa360" },
    { label: "Email", href: "mailto:vishwa.jith360@gmail.com" },
  ],
};

export const workExperience = [
  {
    role: "AI Engineer",
    company: "IBM",
    logoFallback: "IBM",
    period: "Sep 2023 - Present",
    duration: "1 yr 6 mos",
    location: "Bengaluru, Karnataka, India",
    type: "Full-time",
    summary:
      "Designed and deployed scalable Generative AI solutions on watsonx.ai, including customer care chatbots, agentic banking workflows, multimodal RAG, and internal engineering copilots.",
    highlights: [
      "Delivered customer care assistants with digital avatars and enterprise banking agents that improved productivity by up to 69%.",
      "Implemented multimodal RAG, Text2SQL, and Text2MDX pipelines for high-accuracy retrieval and question answering.",
      "Designed AI governance workflows with OpenPages and watsonx.governance for regulatory compliance and explainability.",
      "Built agentic automation solutions for investment recommendations and business operations, reducing capital expenditure and improving efficiency by 35%.",
      "Led a 4-member team building an internal code-generation assistant using MCP, cutting notebook development time by 40%.",
    ],
    techStack: [
      "watsonx.ai",
      "watsonx.governance",
      "OpenPages",
      "Watsonx Orchestrate",
      "Multimodal RAG",
      "Text2SQL",
      "Text2MDX",
      "FastAPI",
      "OpenShift AI",
      "vLLM",
      "MCP",
    ],
  },
  {
    role: "Data Scientist",
    company: "Anheuser-Busch InBev",
    logoFallback: "ABI",
    period: "Jan 2022 - Aug 2023",
    duration: "1 yr 8 mos",
    location: "Bangalore, Karnataka, India",
    type: "Full-time",
    summary:
      "Built forecasting and anomaly detection systems for treasury and supply chain operations, with measurable impact on working capital and inventory accuracy.",
    highlights: [
      "Developed an 8-week cashflow forecasting system using Darts and PyTorch, achieving under 10% MAPE across multiple markets.",
      "Reduced cashflow prediction errors by 30%, improving treasury decision quality and working capital planning.",
      "Implemented anomaly detection pipelines for material inventory discrepancies, improving inventory accuracy by 25%.",
      "Deployed production models on Azure Databricks with monitoring and alerting for performance degradation.",
    ],
    techStack: [
      "Python",
      "PyTorch",
      "Darts",
      "Azure Databricks",
      "Azure Synapse Analytics",
      "Power BI",
      "Streamlit",
      "Docker",
      "Azure Container Registry",
    ],
  },
  {
    role: "Data Scientist",
    company: "Ericsson",
    logoFallback: "E",
    period: "Oct 2018 - Jan 2022",
    duration: "3 yrs 4 mos",
    location: "Noida, Uttar Pradesh, India",
    type: "Full-time",
    summary:
      "Delivered analytics and machine learning solutions for telecom managed services, spanning text classification, KPI anomaly detection, dashboards, and model lifecycle operations.",
    highlights: [
      "Translated business requirements into analytical and ML solutions for network operator clients across regions.",
      "Built text classification workflows that reduced manual ITSM ticket routing time by 60%.",
      "Developed anomaly detection systems for critical network KPIs to support proactive issue resolution.",
      "Managed production model monitoring and transition work across SQL Server, BigQuery, Vertex AI, and Cloud Data Fusion stacks.",
    ],
    techStack: [
      "Python",
      "BigQuery",
      "Vertex AI",
      "Cloud Data Fusion",
      "Tableau",
      "SQL Server",
      "Docker",
      "Cognos",
      "SPSS",
    ],
  },
  {
    role: "Network Engineer - RAN Analyst",
    company: "Ericsson",
    logoFallback: "E",
    period: "Nov 2014 - Sep 2018",
    duration: "3 yrs 11 mos",
    location: "Bengaluru, Karnataka, India",
    type: "Full-time",
    summary:
      "Worked on radio network planning, coverage analysis, and capacity optimization for large-scale telecom operations.",
    highlights: [
      "Performed coverage prediction analysis for new site planning and indoor/outdoor network scenarios.",
      "Identified coverage gaps and optimized antenna parameters to improve network coverage by 15%.",
      "Conducted capacity analysis and monitored post-integration KPIs to maintain service quality.",
    ],
    techStack: ["Python", "SQL Server", "Tableau", "Google Earth", "QGIS"],
  },
];
